posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
	title= StringField('Title', validators=[DataRequired()])
	content = TextAreaField('Content', validators=[DataRequired()])
	submit = SubmitField('Post')
	genre = SelectField('Genre', choices=[("Horror",'Horror'), ('Romance','Romance'), ('Drama', 'Drama'),('Suspense','Suspense'), ('Comedy','Comedy'), ('General', 'General'), ('Sci-fy','Sci-fy')])

main/routes.py
from flask import Blueprint
from flask import render_template, request, Blueprint
from flaskblog.models import Post, User, likes
from flaskblog.main.forms import SearchForm


main=Blueprint('main', __name__)

@main.route("/")
@main.route("/home", methods=['GET', 'POST'])
def home():
	page=request.args.get('page', 1, type=int)
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=1)
	print(posts)
	return render_template('home.html', posts=posts)

@main.route("/about")
def about():
	return "about page"

@main.route("/search", methods=['GET', 'POST'])
def search():
	print('here')
	form=SearchForm()
	if form.validate_on_submit():
		print('this')
		look_for = '%{0}%'.format(form.search.data)
		print(look_for)
		users= User.query.filter(User.username.contains(form.search.data)).all()
		print(users)
		posts= Post.query.filter(Post.title.contains(form.search.data)).all()
		print(posts)
		return render_template('search_result.html', posts=posts, users=users, form=form)
	return render_template('search_result.html', posts=[], users=[], form=form)

posts/routes.py
from flask import Blueprint
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, likes
from flaskblog.posts.forms import PostForm
posts=Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
	form=PostForm()
	if form.validate_on_submit():
		post = Post(title=form.title.data, content=form.content.data, author=current_user, genre=form.genre.data)
		db.session.add(post)
		db.session.commit()
		flash('Your post has been created', 'success')
		return redirect(url_for('main.home'))
	return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
	post = Post.query.get_or_404(post_id)
	if likes.query.filter_by(user_id=current_user.id, post_id=post_id ).first():
		user_liked=1
	else:
		user_liked=0
	return render_template('post.html', title= post.title, post= post, user_liked=user_liked)
	
@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
	post=Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	form = PostForm()
	if form.validate_on_submit():
		flash('Your post has been updated', 'success')
		return redirect(url_for('posts.post', post_id=post.id))
	elif request.method=='GET':
		form.title.data = post.title
		form.genre.data = post.genre
		form.content.data = post.content
	return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
	post=Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash('Your post has been deleted!', 'success')
	return redirect(url_for('main.home'))

@posts.route("/like/<int:post_id>", methods=['GET', 'POST'])
@login_required
def like_post(post_id):
	post = Post.query.get_or_404(post_id)
	if likes.query.filter_by(user_id=current_user.id, post_id=post_id ).first():
		
		post.like_count-=1
		likes.query.filter_by(user_id=current_user.id, post_id=post_id).delete()
		resp=0
	else:

		post.like_count+=1

		like=likes(user_id=current_user.id, post_id=post_id)
		db.session.add(like)
		resp=1
	db.session.commit()
	return redirect(url_for('posts.post',post_id=post_id))

users/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email
import os
users=Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
	if  current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user= User(username=form.username.data, email= form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash("Account created for "+ form.username.data+"!", "success")
		return redirect(url_for('users.login'))
	return render_template('register.html', title='Register', form=form)

@users.route("/login",  methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash("Login unsucessful", "danger")
	return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
	form= UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_picture(form.picture.data)
			current_user.image_file= picture_file
		current_user.username= form.username.data
		current_user.email= form.email.data
		db.session.commit()
		flash("your account has been updated!",'success')
		return redirect(url_for('users.account'))
	elif request.method == "GET":
		form.username.data = current_user.username
		form.email.data = current_user.email
	image_file = url_for('static', filename='profile_pics/'+ current_user.image_file)
	return render_template('account.html', title='Account', image_file= image_file, form=form )


@users.route("/user/<string:username>")
def user_posts(username):
	page=request.args.get('page', 1, type=int)
	user = User.query.filter_by(username=username).first_or_404()
	posts = Post.query.filter_by(author=user)\
	.order_by(Post.date_posted.desc())\
	.paginate(page=page, per_page=1)
	return render_template('user_posts.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('An email has been sent with instructions', 'info')
		return redirect(url_for('users.login'))


	return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user= User.verify_reset_token(token)
	if user is None:
		flash("That is an invalid or expired token", 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password=hashed_password
		db.session.commit()
		flash("Password is update for user "+ user.username +"!", "success")
		return redirect(url_for('users.login'))
	return render_template('reset_token.html', title='Reset Password', form=form)

templates/account.html
{% extends "layout.html" %}
{% block content %}

	<div class="content-section">
		<div class="media">
			<img class ="rounded-circle account-img" src="{{ image_file }}">
			<div calss="media-body">
				<h2 class="account-heading">{{ current_user.username }}</h2>
				<p class="text-secondary">{{ current_user.email }}</p>
			</div>
		</div>

  		<form method="POST" action="" enctype="multipart/form-data">
  			{{ form.hidden_tag()}}
  			<fieldset class="form-group">
  				<legend class="border-bottom mb-4">Update Information</legend>
  				<div class="form-group">
  					{{ form.username.label(class="form-control-label")}}

  					{% if form.username.errors %}
  						{{ form.username(class="form-control for-control-lg is-invalid") }}
  						<div class="invalid-feedback">
  							{% for error in form.username.errors %}
  								<span> {{ error }}
  									
  								</span>
  							{% endfor %}	
  						</div>
  					{% else  %}

  						{{ form.username(class= "form-control form-control-lg")}}

  					{% endif %}
  				</div>

  				<div class="form-group">
  					{{ form.email.label(class="form-control-label")}}

  					{% if form.email.errors %}
  						{{ form.email(class="form-control for-control-lg is-invalid") }}
  						<div class="invalid-feedback">
  							{% for error in form.email.errors %}
  								<span> {{ error }}
  									
  								</span>
  							{% endfor %}	
  						</div>
  					{% else  %}

  						{{ form.email(class= "form-control form-control-lg")}}

  					{% endif %}
  				</div>

  				<div class="form-group">
  					{{ form.picture.label() }}<br>
  					{{ form.picture(class="Form-control-file") }}
  					{%if form.picture.errors %}
  						{% for error in form.picture.errors %}
  							<span> {{ error }}</span><br>
  						{% endfor %}
  					{% endif %}
  					
  				</div>
  			</fieldset>
  			<div class="form-group">
  					{{ form.submit(class="btn btn-outline-info") }}
  				</div>
  			</form>
	</div>

{% endblock content %}

templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  		<form method="POST" action="">
  			{{ form.hidden_tag()}}
  			<fieldset class="form-group">
  				<legend class="border-bottom mb-4">{{ legend }}</legend>
  				<div class="form-group">
  					{{ form.title.label(class="form-control-label")}}

  					{% if form.title.errors %}
  						{{ form.title(class="form-control for-control-lg is-invalid") }}
  						<div class="invalid-feedback">
  							{% for error in form.title.errors %}
  								<span> {{ error }}
  									
  								</span>
  							{% endfor %}	
  						</div>
  					{% else  %}

  						{{ form.title(class= "form-control form-control-lg")}}

  					{% endif %}
  				</div>

  				<div class="form-group">
  					{{ form.content.label(class="form-control-label")}}

  					{% if form.content.errors %}
  						{{ form.content(class="form-control for-control-lg is-invalid") }}
  						<div class="invalid-feedback">
  							{% for error in form.content.errors %}
  								<span> {{ error }}
  									
  								</span>
  							{% endfor %}	
  						</div>
  					{% else  %}

  						{{ form.content(class= "form-control form-control-lg")}}

  					{% endif %}
  				</div>
          {{ form.genre }}
  			</fieldset>
  			<div class="form-group">
  					{{ form.submit(class="btn btn-outline-info") }}
  				</div>
  			</form>
  	</div>
{% endblock content %}

templates/home.html
{% extends "layout.html" %}

{% block content %}
    
  {% for post in posts.items %}
  <script src="static/js/jquery-1.9.0.js"></script>
   <script src="static/js/script.js"></script>

  		<article class="media content-section">
  			<img class="rounded-circle article-img" src="{{ url_for('static',filename='profile_pics/' + post.author.image_file) }}">
  			<div class="media-body">
  				<div class="article-metadata">
  					<a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
  					<small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.genre == "Horror" %}
            <span class="badge badge-dark">{{ post.genre }}</span>
            {% elif post.genre == "Romance" %}
            <span class="badge badge-danger">{{ post.genre }}</span>
            {% elif post.genre == "Comedy" %}
            <span class="badge badge-warning">{{ post.genre }}</span>
            {% elif post.genre == "Suspense" %}
            <span class="badge badge-secondary">{{ post.genre }}</span>
            {% elif post.genre == "Drama" %}
            <span class="badge badge-success">{{ post.genre }}</span>
            {% elif post.genre == "Sci-fy" %}
            <span class="badge badge-info">{{ post.genre }}</span>
            {% else %}
            <span class="badge badge-primary">general</span>
            {% endif %}
   				</div>
   				<h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
   				<p class="article-content">{{ post.content }}</p>
  			</div>
  		</article>

  	{% endfor %}
  	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  		{% if page_num %}
  			{% if posts.page == page_num %}
  			<a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
  			{% else %}
  			<a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
  			{% endif %}
  		{% else %}
  			...

  		{% endif %}
  	{% endfor %}

{% endblock content %}

templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    
    {%if title %}
    	<title>Scaffold - {{ title }}</title>

    {%else%}
    	<title>Scaffold</title>

    {%endif%}

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #67c4f0;">
  <a class="navbar-brand" href="{{ url_for('main.home') }}">Scaffold</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.home') }}">Home <span class="sr-only">(current)</span></a>
      </li>

      {% if current_user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.search') }}">Search</a>
      </li>
    </ul>
  </div>
</nav>
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				{% with messages = get_flashed_messages(with_categories=true) %}
				{% if messages %}
					{% for category,message in messages %}
						<div class="alert alert-{{ category }}">
							{{ message }}
							
						</div>
					{% endfor %}		
				{% endif%}
				{% endwith%}
		{% block content %} {% endblock %}

	</div>
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block content %}
    	<div class="content-section">
  		<form method="POST" action="">
  			{{ form.hidden_tag()}}
  			<fieldset class="form-group">
  				<legend class="border-bottom mb-4">Log In</legend>

  				<div class="form-group">
  					{{ form.email.label(class="form-control-label")}}

  					{% if form.email.errors %}
  						{{ form.email(class="form-control for-control-lg is-invalid") }}
  						<div class="invalid-feedback">
  							{% for error in form.email.errors %}
  								<span> {{ error }}
  									
  								</span>
  							{% endfor %}	
  						</div>
  					{% else  %}

  						{{ form.email(class= "form-control form-control-lg")}}

  					{% endif %}
  				</div>

  				<div class="form-group">
  					{{ form.password.label(class="form-control-label")}}

  					{% if form.password.errors %}
  						{{ form.password(class="form-control for-control-lg is-invalid") }}
  						<div class="invalid-feedback">
  							{% for error in form.password.errors %}
  								<span> {{ error }}
  									
  								</span>
  							{% endfor %}	
  						</div>
  					{% else  %}

  						{{ form.password(class= "form-control form-control-lg")}}

  					{% endif %}
  				</div>
  				<div class="form-check">
  					{{ form.remember(class="form-check-input") }}
  					{{ form.remember.label(class="form-check-label") }}
  					
  				</div>

  			</fieldset>
  			<div class="form-group">
  					{{ form.submit(class="btn btn-outline-info") }}
  				</div>

  			<small class="text-muted ml-2">
  				<a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
        </small>
  		</form>
  	</div>
  	<div class= "border-top pt-3">
  		<small class="text-muted">
  			Don't Have An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign up</a>
  		</small>
  	</div>

{% endblock content %}

templates/post.html
{% extends "layout.html" %}

{% block content %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <link href="static/css/signin.css" rel="stylesheet">
   <script src="{{ url_for('static', filename='js/jquery-1.9.0.js') }}"></script>
   <script src="{{ url_for('static', filename='js/script.js') }}"></script>

  		<article class="media content-section">
  			<img class="rounded-circle article-img" src="{{ url_for('static',filename='profile_pics/' + post.author.image_file) }}">
  			<div class="media-body">
  				<div class="article-metadata">
  					<a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>

            {% if post.genre == "Horror" %}
            <span class="badge badge-dark">{{ post.genre }}</span>
            {% elif post.genre == "Romance" %}
            <span class="badge badge-danger">{{ post.genre }}</span>
            {% elif post.genre == "Comedy" %}
            <span class="badge badge-warning">{{ post.genre }}</span>
            {% elif post.genre == "Suspense" %}
            <span class="badge badge-secondary">{{ post.genre }}</span>
            {% elif post.genre == "Drama" %}
            <span class="badge badge-success">{{ post.genre }}</span>
            {% elif post.genre == "Sci-fy" %}
            <span class="badge badge-info">{{ post.genre }}</span>
            {% else %}
            <span class="badge badge-primary">general</span>
            {% endif %}

  					<small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.author == current_user %}
            <div>
              <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
              <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#exampleModal">Delete</button>
            </div>
            {% endif %}
   				</div>
   				<h2 class="article-title">{{ post.title }}</h2>
   				<p class="article-content">{{ post.content }}</p>
  			</div>
  		</article>
      <font size="6">
      <div class="alert alert-secondary">like count:
      <a class="text-success badge badge-light">{{ post.like_count }}</a>
      </div>

    

      <form action="{{ url_for('posts.like_post', post_id=post.id) }}">
      {% if user_liked== 1 %}
      <button class="btn btn-danger mb-10" type="submit">dislike</button>
      {% else %}
      <button class="btn btn-success mb-4 t-4" type="submit">like</button>
      {% endif %}
      </form>
      </font>
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

templates/reset_request.html
{% extends "layout.html" %}

{% block content %}
    	<div class="content-section">
  		<form method="POST" action="">
  			{{ form.hidden_tag()}}
  			<fieldset class="form-group">
  				<legend class="border-bottom mb-4">Reset Password</legend>

  				<div class="form-group">
  					{{ form.email.label(class="form-control-label")}}

  					{% if form.email.errors %}
  						{{ form.email(class="form-control for-control-lg is-invalid") }}
  						<div class="invalid-feedback">
  							{% for error in form.email.errors %}
  								<span> {{ error }}
  									
  								</span>
  							{% endfor %}	
  						</div>
  					{% else  %}

  						{{ form.email(class= "form-control form-control-lg")}}

  					{% endif %}
  				</div>
  			</fieldset>
  			<div class="form-group">
  					{{ form.submit(class="btn btn-outline-info") }}
  				</div>
  			</form>
  	</div>

{% endblock content %}

templates/search_result.html
{% extends "layout.html" %}

{% block content %}

<form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag()}}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Search</legend>
          <div class="form-group">
            {{ form.search.label(class="form-control-label")}}
            {{ form.search(class= "form-control form-control-lg")}}
          </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
          </div>
        </form>
  {% if posts|length<1 %}
  {% else %}
  <h1 class="border-top">Posts</h1>
   {% for post in posts %}
      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static',filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.genre == "Horror" %}
            <span class="badge badge-dark">{{ post.genre }}</span>
            {% elif post.genre == "Romance" %}
            <span class="badge badge-danger">{{ post.genre }}</span>
            {% elif post.genre == "Comedy" %}
            <span class="badge badge-warning">{{ post.genre }}</span>
            {% elif post.genre == "Suspense" %}
            <span class="badge badge-secondary">{{ post.genre }}</span>
            {% elif post.genre == "Drama" %}
            <span class="badge badge-success">{{ post.genre }}</span>
            {% elif post.genre == "Sci-fy" %}
            <span class="badge badge-info">{{ post.genre }}</span>
            {% else %}
            <span class="badge badge-primary">general</span>
            {% endif %}
          </div>
          <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        </div>
      </article>
    {% endfor %}
    {% endif %}

  {% if users|length<1 %}
  {% else %}  
  <h1 class="border-top">Users</h1>
  {% for user in users %}
      <article class="media content-section">
        <div class="media-body">
          <div class="article">
            <img class="rounded-lg article-img" src="{{ url_for('static',filename='profile_pics/' + user.image_file) }}">
            <font size="6"> 
            <a class="mr-3" href="{{url_for('users.user_posts', username=user.username) }}">{{ user.username }}</a>
            </font>
          </div>
        </div>
      </article>
    {% endfor %}
    {% endif %}
    {% if posts|length<1 and users|length<1 %}
    <h1 class="border-top">Sorry, no posts or users with matched with your search</h1>
    {% endif %}
{% endblock content %}

templates/user_posts.html
{% extends "layout.html" %}

{% block content %}

  <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
  {% for post in posts.items %}
  		<article class="media content-section">
  			<img class="rounded-circle article-img" src="{{ url_for('static',filename='profile_pics/' + post.author.image_file) }}">
  			<div class="media-body">
  				<div class="article-metadata">
  					<a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
  					<small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.genre == "horror" %}
            <a class="text-dark badge badge-">{{ post.genre }}</a>
            {% elif post.genre == "romance" %}
            <a class="text-danger badge badge-">{{ post.genre }}</a>
            {% elif post.genre == "comedy" %}
            <a class="text-warning badge badge-">{{ post.genre }}</a>
            {% elif post.genre == "suspense" %}
            <a class="text-secondary badge badge-">{{ post.genre }}</a>
            {% elif post.genre == "drama" %}
            <a class="text-success badge badge-">{{ post.genre }}</a>
            {% else %}
            <a class="text-primary badge badge-">general</a>
            {% endif %}
   				</div>
   				<h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
   				<p class="article-content">{{ post.content }}</p>
  			</div>
  		</article>
  	{% endfor %}
  	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  		{% if page_num %}
  			{% if posts.page == page_num %}
  			<a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
  			{% else %}
  			<a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts',username=user.username, page=page_num) }}">{{ page_num }}</a>
  			{% endif %}
  		{% else %}
  			...

  		{% endif %}
  	{% endfor %}
{% endblock content %}